import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="pt-24 min-h-[100dvh]">
      <div className="container-width section-padding max-w-3xl">

        <div className="mb-10">
          <p className="text-label font-semibold uppercase tracking-widest text-primary mb-3">Legal</p>
          <h1 className="font-serif text-display text-ink mb-2">Terms &amp; Conditions</h1>
          <p className="text-small text-ink-muted">Last modified: 16.09.2025</p>
        </div>

        <div className="flex flex-col gap-8 text-small text-ink-muted leading-relaxed">

          <section>
            <p>
              This document (&ldquo;Terms&rdquo;) is an electronic record in terms of the Information Technology
              Act, 2000 and rules thereunder, and other applicable law, and is generated by a computer system and
              does not require any physical or digital signatures.
            </p>
            <p className="mt-4">
              Parties are responsible for ensuring that any &ldquo;Personal Data&rdquo; (as defined in the Act) it
              supplies to the Company has been collected within the terms of the Information Technology (Reasonable
              security practices and procedures and sensitive personal data or information) Rules, 2011.
            </p>
            <p className="mt-4">
              The Company agrees to process the data in accordance with lawful and reasonable written instructions
              provided by the parties of this Platform.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">1. Applicability</h2>
            <p>
              The Company, Spectrable Inc. (&ldquo;Company&rdquo; or &ldquo;We&rdquo;), with a registered address
              at 601 Gopal Vishnu CHS Ltd, Mahant Road, Opposite Ruia School, Vile Parle (East),
              Mumbai-400057, Maharashtra, India, operates under the brand name Spectrable and provides a distinct
              feature with the Spectrable AI Chatbot for better healthcare management.
            </p>
            <p className="mt-4">
              These Terms and Conditions apply to the Spectrable platform and its features. By accessing or using
              it, whether as a &ldquo;Caretaker&rdquo; or as a &ldquo;Therapist&rdquo;, you agree to be bound by
              these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">2. Introduction</h2>
            <p>
              These terms and conditions (&ldquo;Terms&rdquo;) govern the use of services made available on or
              through the Spectrable website and/or app (collectively, the &ldquo;Platform&rdquo;, and together
              with the services made available on or through the Platform, the &ldquo;Services&rdquo;).
            </p>
            <p className="mt-4">
              These Terms also include our{" "}
              <Link href="/privacy" className="text-primary hover:text-primary-hover transition-colors">
                privacy policy
              </Link>
              , which forms an essential part of these Terms. By accessing and using the Services, you accept these
              Terms and Conditions.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">3. Purpose and Understanding</h2>
            <p>
              These Conditions shall apply as between the Company and the Therapists and also between the
              Caretakers and Therapists who use the Platform to deliver and receive care services respectively.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">4. Eligibility and Use of Services</h2>
            <p>
              Persons who are &ldquo;incompetent to contract&rdquo; within the meaning of the Indian Contract Act,
              1872, are not eligible to use the Platform. By accessing or using the Platform, you represent and
              warrant that you are of legal age to form a binding contract and are not a person barred from
              receiving services under applicable law.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">19. Disclaimer</h2>
            <p>
              The Platform, including its AI-generated outputs, is intended solely as an assistive digital tool for
              caregivers, therapists, and clients. It is not classified as a medical device and does not constitute
              medical advice, diagnosis, or treatment. Users should always consult qualified healthcare
              professionals for clinical decisions.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">Glossary</h2>
            <ul className="flex flex-col gap-3">
              {[
                {
                  term: "Company, We, Us, or Our",
                  def: "Refers to Spectrable Inc., operating under the Spectrable brand.",
                },
                {
                  term: "Platform",
                  def: "The Company's mobile application, website and/or app, software, and associated services.",
                },
                {
                  term: "Therapist",
                  def: "A licensed or qualified healthcare professional using the Platform to deliver care services.",
                },
                {
                  term: "Caretaker",
                  def: "A parent, guardian, or caregiver using the Platform to support a child receiving care.",
                },
              ].map(({ term, def }) => (
                <li key={term} className="flex items-start gap-2.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 shrink-0" />
                  <span>
                    <strong className="font-semibold text-ink">{term}</strong> &mdash; {def}
                  </span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-h4 text-ink mb-3">Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:admin@spectrablecare.com" className="text-primary hover:text-primary-hover transition-colors">
                admin@spectrablecare.com
              </a>
              .
            </p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-border flex flex-wrap gap-6">
          <Link href="/privacy" className="text-small font-medium text-primary hover:text-primary-hover transition-colors">
            Privacy Policy
          </Link>
          <Link href="/refund-policy" className="text-small font-medium text-primary hover:text-primary-hover transition-colors">
            Cancellation &amp; Refunds
          </Link>
          <Link href="/shipping-policy" className="text-small font-medium text-primary hover:text-primary-hover transition-colors">
            Shipping Policy
          </Link>
        </div>

      </div>
    </main>
  );
}
